Add Java 16 support for java formatting
macisamuele/language-formatters-pre-commit-hooks pull request #73
Opened 2021-07-17 11:32 UTC by ostrya

Proposed fix for #72 .

For now, I did not add an option to disable the additional flags, as they are specific to the java binary and not the actual google formatter jar and are backwards compatible to Java 11.

2021-07-17 12:01 UTC, macisamuele requested changes
Could you please add a CLI argument to disable this new behaviour?
Requesting this because users of the pre-commit might be interested on retaining the old style (maybe because not on Java 16 yet).

... and eventually I failed to mention that... thanks a lot for supporting the project 😊

2021-07-17 12:21 UTC, macisamuele commented
@ostrya I see the aspect of flags being backward compatible on previous java versions, which is good but how does it affect the final "prettified" source code?
Will the flags cause formatting differences or are meant to "silence" the java warnings only?

if no changes in the formatting are present then we could merge it without flags to disable the behaviour but
* ensure that tests with an old version of java are run (add a github action environment where java 15 is in use)
* fix currently broken tests (maybe rebase on latest master if you feel like you have not added the issues)

2021-07-17 17:49 UTC, ostrya commented
The additional parameters do not affect the outcome of the code cleanup, they only allow the google formatter to access some internal classes from the JDK which it needs to parse the code.

As for the broken tests: at least the tests using the google 1.9 formatter version can not work with Java 16, only the 1.10 version is compatible. So for now I reverted the test runner back to using Java 15.

2021-07-17 18:28 UTC, macisamuele commented
@ostrya please address the pre-commit issues and then it looks good to be merged

2021-07-17 18:49 UTC, ostrya commented
Silly me, forgot about installing pre-commit :-)

2021-07-18 16:39 UTC, macisamuele approved these changes

2021-07-18 16:39 UTC, merged